nodeSelector:
  doks.digitalocean.com/node-pool: worker-cluster-payment-pool

image:
  repository: registry.digitalocean.com
  tag: latest

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false
  className: nginx
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: transaction-check-api.example.com
      paths:
        - path: /api/payment
          pathType: Prefix
  tls:
    - secretName: transaction-check-api-tls
      hosts:
        - transaction-check-api.example.com

tolerations:
  - key: "node-for-project.megane.io"
    operator: "Equal"
    value: "payment"
    effect: "NoSchedule"

REDIS_URI: ""
PORT: "3000"
MIN_REPLICA: 1
MAX_REPLICA: 5
TARGET_CPU: 80
TARGET_MEM: 80
IMAGE_REPOSITORY: "kob-bank"  # Your DOCR repository name
IMAGE_NAME: "transaction-check-api"
