nodeSelector:
  doks.digitalocean.com/node-pool: worker-cluster-payment-pool

image:
  repository: registry.digitalocean.com
  tag: latest

service:
  type: NodePort
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: transaction-check-api.example.com
      paths:
        - path: /api/payment
          pathType: Prefix
  tls: []

tolerations:
  - key: "node-for-project.megane.io"
    operator: "Equal"
    value: "payment"
    effect: "NoSchedule"

REDIS_URI: ""
PORT: "3000"
MIN_REPLICA: 1
MAX_REPLICA: 5
TARGET_CPU: 80
TARGET_MEM: 80
IMAGE_REPOSITORY: "kob-payment"  # DOCR repository (same as compay)
IMAGE_NAME: "transaction-check-api"
