apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-check-api.fullname" . }}
  labels:
    app: {{ include "transaction-check-api.name" . }}
    chart: {{ include "transaction-check-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  ports:
  - port: {{ .Values.service.port | default 3000 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ include "transaction-check-api.name" . }}
    release: {{ .Release.Name }}
